---
include:
  - board: xiao_ble//zmk
    shield: eyeslash_corne_central_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyeslash_corne_central_dongle_prospector
  - board: xiao_ble//zmk
    shield: eyeslash_corne_central_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: prospector_operator
  - board: xiao_ble//zmk
    shield: eyeslash_corne_central_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: prospector_radii
  - board: nice_nano//zmk
    shield: eyeslash_corne_peripheral_left nice_view
  - board: nice_nano//zmk
    shield: eyeslash_corne_peripheral_right nice_view
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset_nice_nano_v2
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset_prospector
