manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tokyo2006
      url-base: https://github.com/tokyo2006
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: moonward
      url-base: https://github.com/moonward
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 484a0547078228f6957ed164523823e39fbedec4  # main @ 2026-07-05, needed for Zephyr 4.1 (prospector new-status-screens)
      import: app/west.yml
    - name: prospector-zmk-module                 # <--- and these
      remote: moonward                           # <--- fork: Operator battery redesign (see customize-operator-battery branch)
      revision: bfa76306fc261aa8fd2556a754fe19f85e3762a7  # customize-operator-battery @ 2026-07-08, based on carrefinho feat/new-status-screens
  self:
    path: config
